# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e14d7799d87047a7c7f1c894a7c08e84b7941609718c0d1d802928c962271e7a78fbfc6eea0f04175a405b90825b78731201b622f2096c24e8466ea90a61826a

test:
  secret_key_base: ed2cb9266cb2f50c5d373ae1a12d1eababd0bc048bdcc55a942bbb77a4cd389d5f1b2fb3528b7e5903c4f01b692340ba2a909a88c0bfe569c79dba2df26ff148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
